services:

  proxy:
    build:
      context: .
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
      helloworld_service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN:-8088}:8088"
    networks:
      - app-network

  helloworld_service:
    build:
      context: ../shared/python
      target: aiohttp-hello-service
    networks:
      - app-network
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge